### ISSUE TITLE
Find a Supplier API - v1

### ISSUE THREAD

**Issue by codedavinci** [toursbylocals/tblv3-api#13]
Accordingly to the business guidelines, It's necessary to have a mechanism to find a specific supplier, based on category, field of knowledge (trait) or location. 

**The Flow**: 
1 -  The user would go to a page / select a filter
2 -  User type a location in the location field ( Location is the top filter ) 
3 -  User selects other filters, such as Categories, traits, rating and etc..

## ACS:  

- [x] User should be able to filter by categories
- [x] User should be able to filter by trait
- [x] User should be able to filter by ratings
- [x] User should be able to filter by attributes ( licenses and etc ...)
- [x] User should be able to filter by language
- [x]  User should be able to filter by supplier's name
- [x]  User should be able to filter by supplier's bio

**Comment by jeannejx** [comment]
@sebas-led @Mica-pfl @ecurtosi99 Would you please offer me some suggestions about filter by rating. For example, the input is a number or a range?

**Comment by jeannejx** [comment]
Remove the blocker after confirming in the stand-up. Should be able to search the keywords on supplier's profile(name and bio).
