### ISSUE TITLE
Signup API  v1 - Travellers Support 

### ISSUE THREAD

**Issue by codedavinci** [toursbylocals/tblv3-api#16]
The Traveller / Customer should have a way to create an account into the marketplace platforms. With that being said it's necessary to create an API that support registration into our systems. 

The UX Flow: 
1. User into signup form 
2. Fill up with personal information
3. User receives an email for verification / validation
4. Once email is confirmed
5. User is allowed to login into the marketplace website and set up their wallet.

Exceptions: 
- While email is not verified user cannot login with the account created.

## ACS: 

- Form should collect: first name, last name, password, email
- Email should be unique in our databases. 
- We should be able to identify users that have not confirmed their email.

## ACS Not to be considered in v1
- Once user signs up we should send a confirmation email

**Comment by sebas-led** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RD-team-61a6bf56a3b924001cb03cba/issues/toursbylocals/tblv3-api/16?planning-poker) with ZenHub @codedavinci @DongJoSuh @ecurtosi99 @growebux @jeannejx @Vinnie1959

**Comment by growebux** [comment]
Plan for this ticket:

1. Write the WIP for this ticket.
2. Analyze tasks and check for examples on MTJ.
3. Create a test file to write the initial tests.
4. Commit the tests and request review. {Tests Cases}

5. Follow up

6. Write a feature for each test. 
7. Validate the test with the feature. > test to pass and fail
9. Commit the feature and test. {Feature with Tests}
10. Request Review.

**Comment by codedavinci** [comment]
Not Finished yet, please finish the task.

**Comment by codedavinci** [comment]
DONE AND CHECKED !
