### ISSUE TITLE
SPIKE - Setup Token strategy for user Auth

### ISSUE THREAD

**Issue by codedavinci** [toursbylocals/tblv3-api#17]
It's very important that define the rules of how long should a traffic token should live.
For example FLOW: 

1.  The user logs in.
2.  Server generates a token.
3.  The token has an expiration time bound to it that will determine how long the user can use the website without having. to login again. 

ACS: 
**Question to be answered**
- How long should this token live ?

**Comment by sebas-led** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RD-team-61a6bf56a3b924001cb03cba/issues/toursbylocals/tblv3-api/17?planning-poker) with ZenHub @codedavinci @DongJoSuh @ecurtosi99 @growebux @jeannejx @Vinnie1959

**Comment by jeannejx** [comment]
Microsoft:
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes

Organizations using Oauth:
![](https://i.stack.imgur.com/dC5Ne.png)

Okta:
When using the Okta authorization server, the lifetime of the JWT tokens is hard-coded to the following values:
ID Token: 60 minutes
Access Token: 60 minutes
Refresh Token: 100 days
When using a custom authorization server, the lifetime of the JWT tokens can be configured, as follows:
ID Token: at least 5 minutes, no more than 24 hours (configurable through [Token Inline Hook](https://developer.okta.com/docs/reference/token-hook/#sample-response-to-modify-token-lifetime) feature)
Access Tokens: at least 5 minutes, no more than 24 hours (configurable through [Token Inline Hook](https://developer.okta.com/docs/reference/token-hook/#sample-response-to-modify-token-lifetime) feature or [Access Policies](https://help.okta.com/okta_help.htm?&id=ext-create-access-policies))
Refresh Tokens: at least 10 minutes, possibly unlimited (configurable through [Access Policies](https://help.okta.com/okta_help.htm?&id=ext-create-access-policies))

Spotify: 
Access token will expire after one hour.

Uber:
Access token are valid for 30 days.

Oauth recommendation:
By default, an access token for a custom API is valid for 86400 seconds (24 hours). We recommend that you set the validity period of your token based on the security requirements of your API. For example, an access token that accesses a banking API should expire more quickly than one that accesses a to-do API. 
https://auth0.com/docs/secure/tokens/access-tokens

**Comment by Mica-pfl** [comment]
@sebas-led 

Suggested token durations: 

**Admin Users:** 

Access token - 1 hour

Refresh Token - 24 hs 

**Customer Users:** 

Access token - 24 hs

Billing Access token - 1 hour (could not find a standard here, can we have an access token for payments that is shorter than 24hs)

Refresh Token - Unlimited (user appears to be logged in forever) 

**Supplier Users:** 

Access token - 1 hs

Refresh Token - 30 days (considering Guides would have to check in and check out of tours and for them to have smoother mobile navegation to answer travellers proactively)

**Comment by codedavinci** [comment]
LGTM
