### ISSUE TITLE
SPIKE - Define the email integration platform. 

### ISSUE THREAD

**Issue by codedavinci** [toursbylocals/tblv3-api#18]
As a large enterprise we need a way to connect the business (and other stakeholders) with their email templates (automated). Also the systems need to be able to send automated emails.

## ACS: 
- Which email platform we are going to be using

**Comment by sebas-led** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RD-team-61a6bf56a3b924001cb03cba/issues/toursbylocals/tblv3-api/18?planning-poker) with ZenHub @codedavinci @DongJoSuh @ecurtosi99 @growebux @jeannejx @Vinnie1959

**Comment by sebas-led** [comment]
Marketing will get back on Tuesday (Jul 26th) with the requirements to be considered

**Comment by growebux** [comment]
@codedavinci @jeannejx @DongJoSuh 

I talked with Sebas about this ticket because it will block the task #16 

@sebas-led is clarifying the requirements with the Marketing team after it is done, he will update this ticket.

**Comment by sebas-led** [comment]
Requirements from MKT: https://docs.google.com/document/d/1VUIxad3X7ZUj1IthNsY1vGuqzdxZZVHSEBw7vgmoQXE/edit#

**Comment by growebux** [comment]
@sebas-led Thanks Sebas, 

@codedavinci I would like to hear your opinion Eddie you have a lot of experience :) 

**Requirements from Marketing:**

Must have:
Authentication of emails with SPF, DKIM, DMARC and BIMI

Transactional Emails:

Must have:

1. Authentication of emails with SPF, DKIM, DMARC and BIMI
2. Ability to set up workflows, recognize triggers (like reminders of an upcoming trip, asking for ratings and reviews post-trip, setting up Net Promoter Survey post-trip, etc.)
3. Ability to cross-sell, upsell, and do abandoned cart reminders. If not within transactional emails, we’ll need to pass the data to ActiveCampaign to do it there. May need a third-party plug-in for cross/to upsell regardless of if it’s done via AC or the transactional email system.
4. Editable templates aligned with templates on Active Campaign so they’re all on-brand.
5. CMS to store pictures, etc.
6. Mobile responsive
7. Reporting capabilities
8. Sends
9. Open rate
10. Bounce rate
11. Clicks
12. Ability to edit sender information (Name + address)

Would like to have:

1. AMP?
2. Dedicated IP?
3. eCommerce integration?

What are the platforms that came up to your mind when you read this requirement?

**Comment by codedavinci** [comment]
Sendgrid !
