### ISSUE TITLE
feat(model) - Guide expertise

### ISSUE THREAD

**Issue by jeannejx** [toursbylocals/tblv3-api#33]
Summary: 

We need the Guide expertise collection to store all the attributes needed from the guide/supplier.

Check https://excalidraw.com/#room=8c349cbfd0633549d78c,GcZEPSk72FqDoi17Lsq2Pg for more details.

ACS:

- [ ] Create testing cases based on business requirements
- [ ] Create Expertise model 
- [ ] Default or require certain fields on business rules
   - TBD
- [ ] Pass all the testings cases and reach 100% coverage

**Comment by sebas-led** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RD-team-61a6bf56a3b924001cb03cba/issues/toursbylocals/tblv3-api/33?planning-poker) with ZenHub @codedavinci @DongJoSuh @ecurtosi99 @growebux @jeannejx @martyhurl

**Comment by DongJoSuh** [comment]
The ticket is outdated. We have decided to put 'Expertise' as a field under 'Supplier' collection.
