### ISSUE TITLE
feat(model) - UserSettings

### ISSUE THREAD

**Issue by jeannejx** [toursbylocals/tblv3-api#34]
Summary: 

We need the UserSettings collection to store all the user settings.

Check https://excalidraw.com/#room=8c349cbfd0633549d78c,GcZEPSk72FqDoi17Lsq2Pg for more details.

ACS:

- [x] Create testing cases based on business requirements
- [x] Create userSettings model 
- [x] Default or require certain fields on business rules
    - apps should be either marketplace or kitchen
    - preferred language is required (default english)
    - preferred currency is required (default USD)
    - darkMode default to false
- [x] Pass all the testings cases and reach 100% coverage

**Comment by sebas-led** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RD-team-61a6bf56a3b924001cb03cba/issues/toursbylocals/tblv3-api/34?planning-poker) with ZenHub @DongJoSuh @ecurtosi99 @growebux @jeannejx

**Comment by martyhurl** [comment]
@codedavinci  the ACS states that 'preferred dashboard is required'. As not all users will need this field as they may not have access to any dashboard, can I leave this as not required?
