### ISSUE TITLE
feat(model) - Calendar

### ISSUE THREAD

**Issue by jeannejx** [toursbylocals/tblv3-api#36]
Summary: 

We need the Calendar collection to store unavailable time slot.

Check https://excalidraw.com/#room=8c349cbfd0633549d78c,GcZEPSk72FqDoi17Lsq2Pg for more details.

ACS:

- [ ] Create testing cases based on business requirements
- [ ] Create Calendar model 
- [ ] Default or require certain fields on business rules
   - should store time range and date that is not available
   - make sure to have an optional reason why the time/date is not available (event name)
   - Input required (booking, guide entry, off hours) 
   - must know the user
- [ ] Pass all the testings cases and reach 100% coverage

**Comment by sebas-led** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RD-team-61a6bf56a3b924001cb03cba/issues/toursbylocals/tblv3-api/36?planning-poker) with ZenHub @DongJoSuh @ecurtosi99 @growebux @jeannejx
