### ISSUE TITLE
feat(model) - Reviews

### ISSUE THREAD

**Issue by jeannejx** [toursbylocals/tblv3-api#37]
Summary: 

We need the Reviews collection to store the the review from all users.

Check https://excalidraw.com/#room=8c349cbfd0633549d78c,GcZEPSk72FqDoi17Lsq2Pg for more details.

ACS:

- [x] Create testing cases based on business requirements
- [x] Create Reviews model 
- [x] Default or require certain fields on business rules
   - must be connected to both listing and booking
   - must know who the reviewer is 
   - must know who the receiver is
   - must know when its created
- [x] Pass all the testings cases and reach 100% coverage

**Comment by sebas-led** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RD-team-61a6bf56a3b924001cb03cba/issues/toursbylocals/tblv3-api/37?planning-poker) with ZenHub @DongJoSuh @ecurtosi99 @growebux @jeannejx

**Comment by martyhurl** [comment]
Ticket is mostly done, just sent a quick validation question to @codedavinci
