### ISSUE TITLE
feat(model) - promocodes

### ISSUE THREAD

**Issue by jeannejx** [toursbylocals/tblv3-api#38]
Summary: 

We need the Promocodes collection to store all the promocodes info.

Check https://excalidraw.com/#room=8c349cbfd0633549d78c,GcZEPSk72FqDoi17Lsq2Pg for more details.

ACS:

- [ ] Create testing cases based on business requirements
- [ ] Create Promocodes model 
- [ ] Default or require certain fields on business rules
   - Campaign is required
   - Code is required
   - Value is required
   - Rules: At least two rule are required (usage and expiration)
   - History is default null
- [ ] Pass all the testings cases and reach 100% coverage

We can skip the business rules for now.

**Comment by sebas-led** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RD-team-61a6bf56a3b924001cb03cba/issues/toursbylocals/tblv3-api/38?planning-poker) with ZenHub @DongJoSuh @ecurtosi99 @growebux @jeannejx

**Comment by codedavinci** [comment]
LGTM
